# Generated by Django 4.1.7 on 2023-03-06 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('course', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('language', models.CharField(choices=[('Русский', 'Русский'), ('Английский', 'Английский')], default='russian', max_length=20)),
                ('status', models.CharField(choices=[('Создан', 'Создан'), ('Сейчас идет', 'Сейчас идет'), ('Закончен', 'Закончен'), ('Отменен', 'Отменен')], default='created', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinars', to='course.course')),
                ('students', models.ManyToManyField(blank=True, related_name='webinars_registered', to='student.student')),
                ('teachers', models.ManyToManyField(related_name='webinars', to='teacher.teacher')),
            ],
            options={
                'verbose_name_plural': 'Webinars',
                'ordering': ['start_time'],
            },
        ),
    ]
